import { createAsyncThunk } from '@reduxjs/toolkit';
import axios from 'axios';

export const postProducts = createAsyncThunk(
  'PostProducts',
  async (_, { rejectWithValue, dispatch }) => {
    const products = [
      {
        id: 51,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-1-3',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-23T18:23:02.707Z',
        updatedAt: '2024-10-23T18:28:20.828Z',
        publishedAt: '2024-10-23T18:23:02.667Z',
        locale: 'en',
        image: '/uploads/medium_2_b45b6e32b8.jpg',
        size: [
          {
            id: 163,
            size: 'm',
            qnty: 6,
          },
          {
            id: 164,
            size: 'l',
            qnty: 0,
          },
          {
            id: 165,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 30,
          color: null,
        },
      },
      {
        id: 50,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-2-5',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-23T18:23:02.617Z',
        updatedAt: '2024-10-23T18:28:07.871Z',
        publishedAt: '2024-10-23T18:23:02.571Z',
        locale: 'en',
        image: '/uploads/medium_5_b145c4d854.webp',
        size: [
          {
            id: 160,
            size: 'm',
            qnty: 6,
          },
          {
            id: 161,
            size: 'l',
            qnty: 0,
          },
          {
            id: 162,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 29,
          color: null,
        },
      },
      {
        id: 28,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-25',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:46:33.224Z',
        updatedAt: '2024-10-22T17:46:34.485Z',
        publishedAt: '2024-10-22T17:46:34.479Z',
        locale: 'en',
        image: '/uploads/medium_6_e3b9e5d052.webp',
        size: [
          {
            id: 88,
            size: 'm',
            qnty: 6,
          },
          {
            id: 89,
            size: 'l',
            qnty: 0,
          },
          {
            id: 90,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 28,
          color: 'Camel Brown',
        },
      },
      {
        id: 27,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 40,
        new: false,
        sale: true,
        oldPrice: 56,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-24',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:46:24.616Z',
        updatedAt: '2024-10-22T17:46:25.701Z',
        publishedAt: '2024-10-22T17:46:25.696Z',
        locale: 'en',
        image: '/uploads/medium_3_69e6c5e085.webp',
        size: [
          {
            id: 84,
            size: 's',
            qnty: 0,
          },
          {
            id: 85,
            size: 'm',
            qnty: 6,
          },
          {
            id: 86,
            size: 'l',
            qnty: 0,
          },
          {
            id: 87,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 27,
          color: 'Dark Stone',
        },
      },
      {
        id: 26,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-23',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:46:15.315Z',
        updatedAt: '2024-10-22T17:46:16.186Z',
        publishedAt: '2024-10-22T17:46:16.180Z',
        locale: 'en',
        image: '/uploads/medium_6_e3b9e5d052.webp',
        size: [
          {
            id: 81,
            size: 'm',
            qnty: 6,
          },
          {
            id: 82,
            size: 'l',
            qnty: 0,
          },
          {
            id: 83,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 26,
          color: 'Camel Brown',
        },
      },
      {
        id: 25,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-22',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:46:08.080Z',
        updatedAt: '2024-10-22T17:46:08.978Z',
        publishedAt: '2024-10-22T17:46:08.969Z',
        locale: 'en',
        image: '/uploads/medium_1_919954fd46.webp',
        size: [
          {
            id: 78,
            size: 'm',
            qnty: 6,
          },
          {
            id: 79,
            size: 'l',
            qnty: 0,
          },
          {
            id: 80,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 25,
          color: 'Black',
        },
      },
      {
        id: 24,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 40,
        new: false,
        sale: true,
        oldPrice: 56,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-21',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:45:39.081Z',
        updatedAt: '2024-10-22T17:45:40.277Z',
        publishedAt: '2024-10-22T17:45:40.271Z',
        locale: 'en',
        image: '/uploads/medium_3_69e6c5e085.webp',
        size: [
          {
            id: 74,
            size: 's',
            qnty: 0,
          },
          {
            id: 75,
            size: 'm',
            qnty: 6,
          },
          {
            id: 76,
            size: 'l',
            qnty: 0,
          },
          {
            id: 77,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 24,
          color: 'Dark Stone',
        },
      },
      {
        id: 23,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-20',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:45:30.634Z',
        updatedAt: '2024-10-22T17:45:31.853Z',
        publishedAt: '2024-10-22T17:45:31.842Z',
        locale: 'en',
        image: '/uploads/medium_6_e3b9e5d052.webp',
        size: [
          {
            id: 71,
            size: 'm',
            qnty: 6,
          },
          {
            id: 72,
            size: 'l',
            qnty: 0,
          },
          {
            id: 73,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 23,
          color: 'Camel Brown',
        },
      },
      {
        id: 22,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 40,
        new: false,
        sale: true,
        oldPrice: 56,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-19',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:45:22.415Z',
        updatedAt: '2024-10-22T17:45:23.470Z',
        publishedAt: '2024-10-22T17:45:23.463Z',
        locale: 'en',
        image: '/uploads/medium_3_69e6c5e085.webp',
        size: [
          {
            id: 67,
            size: 's',
            qnty: 0,
          },
          {
            id: 68,
            size: 'm',
            qnty: 6,
          },
          {
            id: 69,
            size: 'l',
            qnty: 0,
          },
          {
            id: 70,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 22,
          color: 'Dark Stone',
        },
      },
      {
        id: 21,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-18',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:45:06.226Z',
        updatedAt: '2024-10-22T17:45:07.304Z',
        publishedAt: '2024-10-22T17:45:07.297Z',
        locale: 'en',
        image: '/uploads/medium_1_919954fd46.webp',
        size: [
          {
            id: 64,
            size: 'm',
            qnty: 6,
          },
          {
            id: 65,
            size: 'l',
            qnty: 0,
          },
          {
            id: 66,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 21,
          color: 'Black',
        },
      },
      {
        id: 20,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-17',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:44:56.885Z',
        updatedAt: '2024-10-22T17:44:57.826Z',
        publishedAt: '2024-10-22T17:44:57.820Z',
        locale: 'en',
        image: '/uploads/medium_6_e3b9e5d052.webp',
        size: [
          {
            id: 61,
            size: 'm',
            qnty: 6,
          },
          {
            id: 62,
            size: 'l',
            qnty: 0,
          },
          {
            id: 63,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 20,
          color: 'Camel Brown',
        },
      },
      {
        id: 18,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 40,
        new: false,
        sale: true,
        oldPrice: 56,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-15',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:44:29.305Z',
        updatedAt: '2024-10-22T17:44:30.466Z',
        publishedAt: '2024-10-22T17:44:30.458Z',
        locale: 'en',
        image: '/uploads/medium_3_69e6c5e085.webp',
        size: [
          {
            id: 54,
            size: 's',
            qnty: 0,
          },
          {
            id: 55,
            size: 'm',
            qnty: 6,
          },
          {
            id: 56,
            size: 'l',
            qnty: 0,
          },
          {
            id: 57,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 18,
          color: 'Dark Stone',
        },
      },
      {
        id: 17,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-14',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:44:18.756Z',
        updatedAt: '2024-10-22T17:44:19.697Z',
        publishedAt: '2024-10-22T17:44:19.691Z',
        locale: 'en',
        image: '/uploads/medium_6_e3b9e5d052.webp',
        size: [
          {
            id: 51,
            size: 'm',
            qnty: 6,
          },
          {
            id: 52,
            size: 'l',
            qnty: 0,
          },
          {
            id: 53,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 17,
          color: 'Camel Brown',
        },
      },
      {
        id: 15,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-12',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:43:54.908Z',
        updatedAt: '2024-10-22T17:43:55.780Z',
        publishedAt: '2024-10-22T17:43:55.774Z',
        locale: 'en',
        image: '/uploads/medium_1_919954fd46.webp',
        size: [
          {
            id: 44,
            size: 'm',
            qnty: 6,
          },
          {
            id: 45,
            size: 'l',
            qnty: 0,
          },
          {
            id: 46,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 15,
          color: 'Black',
        },
      },
      {
        id: 14,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-11',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:43:44.938Z',
        updatedAt: '2024-10-22T17:43:45.779Z',
        publishedAt: '2024-10-22T17:43:45.773Z',
        locale: 'en',
        image: '/uploads/medium_6_e3b9e5d052.webp',
        size: [
          {
            id: 41,
            size: 'm',
            qnty: 6,
          },
          {
            id: 42,
            size: 'l',
            qnty: 0,
          },
          {
            id: 43,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 14,
          color: 'Camel Brown',
        },
      },
      {
        id: 13,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 40,
        new: false,
        sale: true,
        oldPrice: 56,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-10',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:43:36.549Z',
        updatedAt: '2024-10-22T17:43:37.419Z',
        publishedAt: '2024-10-22T17:43:37.410Z',
        locale: 'en',
        image: '/uploads/medium_3_69e6c5e085.webp',
        size: [
          {
            id: 37,
            size: 's',
            qnty: 0,
          },
          {
            id: 38,
            size: 'm',
            qnty: 6,
          },
          {
            id: 39,
            size: 'l',
            qnty: 0,
          },
          {
            id: 40,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 13,
          color: 'Dark Stone',
        },
      },
      {
        id: 12,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-9',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:43:26.359Z',
        updatedAt: '2024-10-22T17:43:27.256Z',
        publishedAt: '2024-10-22T17:43:27.245Z',
        locale: 'en',
        image: '/uploads/medium_6_e3b9e5d052.webp',
        size: [
          {
            id: 34,
            size: 'm',
            qnty: 6,
          },
          {
            id: 35,
            size: 'l',
            qnty: 0,
          },
          {
            id: 36,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 12,
          color: 'Camel Brown',
        },
      },
      {
        id: 11,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-8',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:43:07.022Z',
        updatedAt: '2024-10-22T17:43:09.107Z',
        publishedAt: '2024-10-22T17:43:09.098Z',
        locale: 'en',
        image: '/uploads/medium_6_e3b9e5d052.webp',
        size: [
          {
            id: 31,
            size: 'm',
            qnty: 6,
          },
          {
            id: 32,
            size: 'l',
            qnty: 0,
          },
          {
            id: 33,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 11,
          color: 'Camel Brown',
        },
      },
      {
        id: 10,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 40,
        new: true,
        sale: true,
        oldPrice: 56,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: true,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-7',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:42:48.481Z',
        updatedAt: '2024-10-22T19:31:57.379Z',
        publishedAt: '2024-10-22T17:42:49.576Z',
        locale: 'en',
        image: '/uploads/medium_3_69e6c5e085.webp',
        size: [
          {
            id: 27,
            size: 's',
            qnty: 0,
          },
          {
            id: 28,
            size: 'm',
            qnty: 6,
          },
          {
            id: 29,
            size: 'l',
            qnty: 0,
          },
          {
            id: 30,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 10,
          color: 'Dark Stone',
        },
      },
      {
        id: 9,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-6',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:42:38.088Z',
        updatedAt: '2024-10-22T17:42:38.978Z',
        publishedAt: '2024-10-22T17:42:38.972Z',
        locale: 'en',
        image: '/uploads/medium_6_e3b9e5d052.webp',
        size: [
          {
            id: 24,
            size: 'm',
            qnty: 6,
          },
          {
            id: 25,
            size: 'l',
            qnty: 0,
          },
          {
            id: 26,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 9,
          color: 'Camel Brown',
        },
      },
      {
        id: 8,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-5',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:42:29.154Z',
        updatedAt: '2024-10-22T17:42:30.206Z',
        publishedAt: '2024-10-22T17:42:30.197Z',
        locale: 'en',
        image: '/uploads/medium_1_919954fd46.webp',
        size: [
          {
            id: 21,
            size: 'm',
            qnty: 6,
          },
          {
            id: 22,
            size: 'l',
            qnty: 0,
          },
          {
            id: 23,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 8,
          color: 'Black',
        },
      },
      {
        id: 7,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-4',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:42:19.941Z',
        updatedAt: '2024-10-22T17:42:20.904Z',
        publishedAt: '2024-10-22T17:42:20.893Z',
        locale: 'en',
        image: '/uploads/medium_1_919954fd46.webp',
        size: [
          {
            id: 18,
            size: 'm',
            qnty: 6,
          },
          {
            id: 19,
            size: 'l',
            qnty: 0,
          },
          {
            id: 20,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 7,
          color: 'Black',
        },
      },
      {
        id: 6,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-3',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:42:06.470Z',
        updatedAt: '2024-10-22T17:42:07.537Z',
        publishedAt: '2024-10-22T17:42:07.523Z',
        locale: 'en',
        image: '/uploads/medium_1_919954fd46.webp',
        size: [
          {
            id: 15,
            size: 'm',
            qnty: 6,
          },
          {
            id: 16,
            size: 'l',
            qnty: 0,
          },
          {
            id: 17,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 6,
          color: 'Black',
        },
      },
      {
        id: 5,
        title: "Women's Montavilla™ Hooded Cardigan",
        category: 'clothing',
        price: 56,
        new: false,
        sale: false,
        oldPrice: null,
        brand: 'Columbia',
        pageCategory: "women's",
        clearance: false,
        techDescription:
          'Hand pockets for small items\n- Ribbed cuffs\n- Center Back Length: 35.0 in / 88.9 cm\n- Imported',
        description: null,
        slug: 'women-s-montavilla-hooded-cardigan-2',
        showOnBanner: false,
        showOnCategoryBanner: false,
        equipmentCategory: 'null',
        lampsLanternsCategory: 'null',
        campSleepCategory: 'null',
        toolsGearCategory: 'null',
        otherCategory: 'null',
        clothingCategory: 'jackets',
        footwearCategory: 'null',
        accessoriesCategory: 'null',
        activityCategory: 'null',
        createdAt: '2024-10-22T17:41:51.748Z',
        updatedAt: '2024-10-22T17:41:53.573Z',
        publishedAt: '2024-10-22T17:41:53.551Z',
        locale: 'en',
        image: '/uploads/medium_1_919954fd46.webp',
        size: [
          {
            id: 12,
            size: 'm',
            qnty: 6,
          },
          {
            id: 13,
            size: 'l',
            qnty: 0,
          },
          {
            id: 14,
            size: 'xl',
            qnty: 5,
          },
        ],
        color: {
          id: 5,
          color: 'Black',
        },
      },
    ];

    try {
      for (const product of products) {
        // Создаем payload внутри цикла и сразу используем его в запросе
        const uniqueSlug = `${product.slug}-${product.id}`;
        const response = await axios.post(
          `https://shop-z684.onrender.com/api/products`,
          {
            data: {
              // Обертываем данные в объект data
              title: product.title,
              image: null,
              category: product.category,
              price: product.price,
              new: product.new,
              sale: product.sale,
              oldPrice: product.oldPrice,
              brand: product.brand,
              size: product.size.map((s) => ({
                id: s.id,
                size: s.size,
                qnty: s.qnty,
              })),
              color: product.color,
              pageCategory: product.pageCategory,
              clearance: product.clearance,
              techDescription: product.techDescription,
              description: product.description,
              slug: uniqueSlug,
              showOnBanner: product.showOnBanner,
              showOnCategoryBanner: product.showOnCategoryBanner,
              equipmentCategory: product.equipmentCategory,
              lampsLanternsCategory: product.lampsLanternsCategory,
              campSleepCategory: product.campSleepCategory,
              toolsGearCategory: product.toolsGearCategory,
              otherCategory: product.otherCategory,
              clothingCategory: product.clothingCategory,
              footwearCategory: product.footwearCategory,
              accessoriesCategory: product.accessoriesCategory,
              activityCategory: product.activityCategory,
            },
          },
          {
            headers: {
              'Content-Type': 'application/json',
            },
          },
        );
      }

      if (!response.data) {
        throw new Error('error');
      }

      return response.data;
    } catch (e) {
      return rejectWithValue('Что-то случилось ( ');
    }
  },
);
